import type { Plugin } from 'vite'
import { resolve, join } from 'node:path'
import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { glob } from 'glob'
import { filePathToPath } from './util'

export type TypeMergeOptions = {
  outDir?: string
  apiTypesFile?: string
}

export const defaultOption: Required<TypeMergeOptions> = {
  outDir: 'src/client/lib',
  apiTypesFile: 'api.d.ts'
}

/**
 * 型定義ファイルから型情報を抽出する関数
 */
function extractTypeBlock(content: string, routePath: string): string | null {
  try {
    // "/"または[x: string]のパターンを探す
    let typeBlock: string | null = null
    
    if (content.includes('[x: string]')) {
      // パラメータパスの場合
      const startMatch = content.match(/\[x: string\]: {/);
      if (startMatch) {
        const startPos = content.indexOf(startMatch[0]);
        let braceCount = 1;
        let endPos = startPos + startMatch[0].length;
        
        // 対応する閉じ括弧を見つける
        while (braceCount > 0 && endPos < content.length) {
          if (content[endPos] === '{') braceCount++;
          if (content[endPos] === '}') braceCount--;
          endPos++;
        }
        
        // 型定義ブロックを抽出
        if (braceCount === 0) {
          typeBlock = `"${routePath}": ${content.substring(startPos + '[x: string]:'.length, endPos)};`;
        }
      }
    } else {
      // 通常のパス
      const pathPattern = /"\/"\s*:\s*{/;
      const pathMatch = content.match(pathPattern);
      
      if (pathMatch) {
        const startPos = content.indexOf(pathMatch[0]);
        let braceCount = 1;
        let endPos = startPos + pathMatch[0].length;
        
        // 対応する閉じ括弧を見つける
        while (braceCount > 0 && endPos < content.length) {
          if (content[endPos] === '{') braceCount++;
          if (content[endPos] === '}') braceCount--;
          endPos++;
        }
        
        // 型定義ブロックを抽出
        if (braceCount === 0) {
          typeBlock = `"${routePath}": ${content.substring(startPos + pathMatch[0].length - 1, endPos)};`;
        }
      }
    }
    
    return typeBlock;
  } catch (error) {
    console.error(`Error extracting type block for ${routePath}:`, error);
    return null;
  }
}

/**
 * すべての型定義ファイルをフラットに結合する関数
 */
function mergeTypeDefinitionsFlat(outDir: string, apiTypesFile: string): void {
  const apiDir = '.typegen/api'
  const outputFile = resolve(outDir, apiTypesFile)
  
  try {
    // ディレクトリが存在することを確認
    if (!existsSync(apiDir)) {
      console.warn(`Warning: Directory ${apiDir} does not exist. No type definitions will be merged.`)
      return
    }
    
    // 型定義ファイルを検索
    const files = glob.sync(`${apiDir}/**/*.d.ts`)
    
    // ルートごとの型定義を保存するマップ
    const routeDefinitions: Map<string, string> = new Map()
    
    // 各ファイルから型定義を抽出
    for (const file of files) {
      const relativePath = file.replace(process.cwd(), '').substring(1)
      // 宣言ファイル(.d.ts)用にincludeDeclaration=trueを指定
      let routePath = filePathToPath(relativePath.replace(new RegExp(`^${outDir}/api`), ''), { includeDeclaration: true })
      
      // "/typegen/api/" プレフィックスを削除
      routePath = routePath.replace(/^\/typegen\/api/, '')
      // ルートパスが空になった場合は "/" に設定
      if (!routePath) routePath = '/'
      
      // ファイル内容を読み込む
      const content = readFileSync(file, 'utf-8')
      
      // 型定義ブロックを抽出
      const typeBlock = extractTypeBlock(content, routePath)
      
      if (typeBlock) {
        routeDefinitions.set(routePath, typeBlock)
      }
    }
    
    // 結合された型定義ファイルを生成
    let mergedContent = `// Generated by typemerge-plugin\n\n`
    mergedContent += `declare const app: import('hono/hono-base').HonoBase<{}, {\n`
    
    // 各ルート定義を統合
    for (const [_, definition] of routeDefinitions.entries()) {
      mergedContent += `    ${definition}\n`
    }
    
    mergedContent += `}, "/">;\n`
    mergedContent += `export default app;\n`
    
    // 結合されたファイルを書き込む
    writeFileSync(outputFile, mergedContent)
    console.log(`✅ Merged API types written to ${outputFile}`)
  } catch (error) {
    console.error('Error merging type definitions:', error)
  }
}

/**
 * 型定義ファイルをマージするViteプラグイン
 * typegen.tsで生成された型定義ファイルを利用する
 */
export function typeMergePlugin(options: TypeMergeOptions = {}): Plugin {
  const { 
    outDir = defaultOption.outDir,
    apiTypesFile = defaultOption.apiTypesFile
  } = options

  return {
    name: 'vite-plugin-type-merge',
    enforce: 'post',
    apply: (_, { command, mode }) => {
      return command === 'build' && mode === 'typegen'
    },
    closeBundle() {
      console.log('TypeMerge: Merging type definitions...')
      mergeTypeDefinitionsFlat(outDir, apiTypesFile)
    }
  }
}

export default typeMergePlugin 
