// Generated by typemerge-plugin

declare const app: import('hono/hono-base').HonoBase<{}, {
    "/todos": {
        $get: {
            input: {};
            output: {
                todos: {
                    id: number;
                    title: string;
                    completed: boolean;
                }[];
            };
            outputFormat: "json";
            status: import('hono/utils/http-status').ContentfulStatusCode;
        };
    };
    "/": {
        $get: {
            input: {};
            output: {
                message: string;
            };
            outputFormat: "json";
            status: import('hono/utils/http-status').ContentfulStatusCode;
        };
    };
    "/users/:id/items/:itemId":  {
        $get: {
            input: {
                param: {
                    id: string;
                    itemId: string;
                };
            };
            output: {
                userId: number;
                itemId: number;
                name: string;
                price: number;
                description: string;
                rating: string;
                inStock: boolean;
                createdAt: string;
            };
            outputFormat: "json";
            status: 200;
        };
    };
    "/posts/:id":  {
        $get: {
            input: {
                param: {
                    id: string;
                };
            };
            output: {
                id: string;
                title: string;
                content: string;
                author: string;
                createdAt: string;
            };
            outputFormat: "json";
            status: 200;
        };
    };
}, "/">;
export default app;
